### ISSUE TITLE
Enable top menu bar

### ISSUE THREAD

**Issue by theramiyer** [theramiyer/typographical-hugo#1]
The top menu bar in Typographical (Jekyll) has about, archive, etc. Enable this on the Hugo port.

**Comment by theramiyer** [comment]
This is already enabled. In order for the menu to appear the same as https://blog.ramiyer.me, add the following to your site's `config.toml`

```toml
[menu]
  [[menu.main]]
    identifier = "about"
    pre = "<i class=\"fa fa-info\" aria-hidden=\"true\"></i>"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "archive"
    pre = "<i class=\"fa fa-archive\" aria-hidden=\"true\"></i>"
    url = "/archive/"
    weight = 2

# and so on
```
